if: env(TRAVIS_TAG) IS present
dist: xenial
services:
  - docker
script:
  - docker build -t ankitjain28/coreos-duo:v$TRAVIS_TAG .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ankitjain28/coreos-duo:v$TRAVIS_TAG
  - docker push ankitjain28/coreos-duo:v$TRAVIS_TAG
